#!/bin/sh
OPTIONS=$(grep -v ^# SBSConf.txt)
PLATFORM=$(uname -a|awk '{print $1" "$15};')
if [ "$PLATFORM" = "Darwin x86_64" ]; then
    # XXX OpenSSL ./config forces me to do this
    ./Configure darwin64-x86_64-cc $OPTIONS
else
    ./config $OPTIONS
fi
make -j2 depend
