#!/bin/sh -e
make -j2 build_crypto
gcc -O3 -Wall -I include -I. -o speed apps/apps.c apps/speed.c libcrypto.a
gcc -O3 -Wall -I include -o ectest crypto/ec/ectest.c libcrypto.a
g++ -O3 -Wall -I include -o ecspeed crypto/ec/ecspeed.c libcrypto.a
